Remove erroneous block end
This is causing the following error on load:

```
SCDoc: Indexing help-files...
SCDoc: Indexed 2448 documents in 1.07 seconds
ERROR: In /home/joe/.local/share/SuperCollider/Extensions/Modality/Modality/HelpSource/Tutorials/How_to_create_a_description_file_for_MIDI.schelp:
  At line 135: syntax error, unexpected ::, expecting end of file
```